[Background]
SolidColor=14,14,14,205

[Line]
SolidColor=255,255,255,255

[Time]
FontFace="Roboto Light"
FontSize=(80*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[Period]
FontFace="Roboto Light"
FontSize=(20*#Scale#)
FontColor=255,255,255,255
StringCase=Lower
AntiAlias=1

[Date]
FontFace="Roboto Condensed Light"
FontSize=(40*#Scale#)
FontColor=255,255,255,255
StringCase=Upper
AntiAlias=1

[Location]
FontFace="Roboto Light"
FontSize=(18*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[Temp]
FontFace="Roboto Light"
FontSize=(30*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[Wind]
FontFace="Roboto Light"
FontSize=(10*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[WindUnit]
FontFace="Roboto Light"
FontSize=(7.5*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[Status]
FontFace="Roboto Light"
FontSize=(13*#Scale#)
FontColor=77,191,217,255
AntiAlias=1

[ForecastDay]
FontFace="Roboto Condensed Light"
FontSize=(13*#Scale#)
FontColor=255,255,255,255
StringCase=Upper
AntiAlias=1

[ForecastTemp]
FontFace="Roboto Light"
FontSize=(13*#Scale#)
FontColor=145,145,145,255
AntiAlias=1

[MonitorTitle]
FontFace="Roboto Condensed Light"
FontSize=(13*#Scale#)
FontColor=255,255,255,255
AntiAlias=1
StringCase=Upper

[MonitorValue]
FontFace="Roboto Light"
FontSize=(13*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[MonitorUnit]
FontFace="Roboto Light"
FontSize=(10*#Scale#)
FontColor=255,255,255,255
AntiAlias=1

[MonitorGraph]
SolidColor=28,28,28,255
W=(180*#Scale#)
H=(38*#Scale#)

[MonitorLine]
AntiAlias=1
LineWidth=2
W=(180*#Scale#)
H=(38*#Scale#)